version: '3'
services:
    memoet:
      image: manhtai/memoet:latest
      ports:
        - "4000:4000"
      depends_on:
        - postgres
      build:
        context: .
      environment:
        DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
        SECRET_KEY_BASE: "B/JNbadChrAhO/LcuQA4TU5iCeQzMNV/Qdm529OugebfosRj7B6El9cUi2Vg5C0h7rtlogEnOQhP/LwcDRIfOw=="
        URL_HOST: "${URL_HOST:-localhost}"
        URL_SCHEMA: "${URL_SCHEMA:-http}"
        URL_PORT: "${URL_PORT:-4000}"

    postgres:
      image: postgres:13
      environment:
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
        - pgdata:/var/lib/postgresql/data/pgdata
      ports:
        - "${DATABASE_PORT:-5432}:5432"

volumes:
    pgdata:
