name: Memoet CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      ELIXIR_ENV: test
      DATABASE_HOST: localhost
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: postgres
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: "postgres"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.19"
          otp-version: "28.1.1"
          version-type: "strict"

      - name: Install dependencies
        run: mix deps.get

      - name: Run cargo test
        run: cargo test --manifest-path native/sm2/Cargo.toml

      - name: Run mix test
        run: mix coveralls

      - name: Install assets dependencies
        run: npm install --prefix assets

      - name: Run assets deploy
        run: npm run deploy --prefix assets
